export const FETCH: any = {
  ENTITY: {
    START: 'FETCH_ENTITY_START',
    SUCCESS: 'FETCH_ENTITY_SUCCESS',
    FAIL: 'FETCH_ENTITY_FAIL',
  },
  POSTS: {
    START: 'FETCH_POSTS_START',
    SUCCESS: 'FETCH_POSTS_SUCCESS',
    FAIL: 'FETCH_POSTS_FAIL',
  },
  POST_BY_ID: {
    START: 'FETCH_POST_BY_ID_START',
    SUCCESS: 'FETCH_POST_BY_ID_SUCCESS',
    FAIL: 'FETCH_POST_BY_ID_FAIL',
  },
  ADD_POST: {
    START: 'FETCH_ADD_POST_START',
    SUCCESS: 'FETCH_ADD_POST_SUCCESS',
    FAIL: 'FETCH_ADD_POST_FAIL',
  },
  REPLIES: {
    START: 'FETCH_REPLIES_START',
    SUCCESS: 'FETCH_REPLIES_SUCCESS',
    FAIL: 'FETCH_REPLIES_FAIL',
  }
};
